### ISSUE TITLE
Parser.Param fails if block/section has a period in it

### ISSUE THREAD

**Issue by knightzac19** [Ajnasz/IniReader#10]
Another small issue I found is that because you have it so that you can do **block.key** to get the key, if the block has a period in it , it fails to pull the key obviously. I am able to get around it by using your array method for the function.

So if I do
```
parser.param(["/script/shootergame.shootergamemode","MaxNumberOfPlayersInTribe"]);
```
it will work fine, but if I use the string way,

```
parser.param("/script/shootergame.shootergamemode.MaxNumberOfPlayersInTribe");
```
I'll get a lovely "shootergamemode" undefined error and such.

Here's the block/section that is causing the issue in my INI file.
```
[/script/shootergame.shootergamemode]
```

**Comment by Ajnasz** [comment]
Hey @knightzac19!

See the period-in-block-name branch for possible solutions.

Hope it helps.

**Comment by Ajnasz** [comment]
I also merged master into the branch, so you can test out with the other fixes made for your issue requests!

**Comment by knightzac19** [comment]
That worked perfectly as well. You're on a roll today.
