### ISSUE TITLE
Allow disabling of header

### ISSUE THREAD

**Issue by SquareByte** [Ajnasz/IniReader#16]
For my use-case it is detrimental that a header is written on every write():
```ini
; IniReader
; 2023-03-02


```
I see the use case, but would like a flag for the write() method to disable the header lines altogether. 

PS: Also, to make this feature more useful, I'd suggest to put the version of IniReader in the first line.

**Comment by SquareByte** [comment]
I made a pull request with a simple third arg to write(). Added docs. Tests still work.

**Comment by Ajnasz** [comment]
Published in [2.2.0](https://www.npmjs.com/package/inireader/v/2.2.0)
Thank you for your help
