### ISSUE TITLE
'fileWritten' emitted even if an error occurs

### ISSUE THREAD

**Issue by ikogan** [Ajnasz/IniReader#6]
It seems that if there's an error writing to a file, say a permission issue, both 'error' and 'fileWritten' is emitted. This makes error handling a little difficult. I think that puttin the emit in an else block around https://github.com/Ajnasz/IniReader/blob/master/lib/inireadercore.js#L515 would take care of it.

**Comment by Ajnasz** [comment]
Thanks, I fixed it. see 0.3.4
