### ISSUE TITLE
Changing license

### ISSUE THREAD

**Issue by Ajnasz** [Ajnasz/IniReader#7]
Hi @pivaldi @udondan @roncli,

I'm planning to change the license of the package from GPLv2 to MIT, and as contributors I want to ask your permission to that. Would you mind it?

Thanks

**Comment by roncli** [comment]
That works for me.

**Comment by pivaldi** [comment]
No problem for me too.

**Comment by udondan** [comment]
Of course not, go ahead. :)

**Comment by Ajnasz** [comment]
Thank you guys!
