### ISSUE TITLE
Parser can't parse brackets.

### ISSUE THREAD

**Issue by knightzac19** [Ajnasz/IniReader#8]
With the current regex the parser cannot parse something like this **PerLevelStatsMultiplier_Player[0]=1.0**. I've put in a known ini regex in and it fixed the issue.

This is the regex I'm using now, `keyValueRex = /^([^=;\r\n]+)=([^;\r\n]*)/,`. It finds the brackets properly and the rest of the parser is working as intended.

**Comment by Ajnasz** [comment]
Hi!

Could you test it with 1147f38?

Thanks

**Comment by knightzac19** [comment]
Works perfect for the brackets, but breaks the ability to get keys with spaces in them, such as

 `Cloth Boots=1`

**Comment by Ajnasz** [comment]
Thanks!

Could you test with 70f2e333684d1251b?

**Comment by knightzac19** [comment]
Looks like that worked perfect for both instances.
