### ISSUE TITLE
Parser can't parse keys with same name.

### ISSUE THREAD

**Issue by knightzac19** [Ajnasz/IniReader#9]
This might be more of a feature than a bug, I have yet to find any parsers to do this properly. However, I was able to modify the parse code slightly to get this to work.

Lines 310-322 now look like this in the inireadercore.js:

			
var temp = output[currentSection][keyVal.key];
						//this means we have duplicate keys
						if(output[currentSection][keyVal.key] !== undefined) {
							if(Array.isArray(output[currentSection][keyVal.key]) === false) {
								output[currentSection][keyVal.key] = [];
								output[currentSection][keyVal.key].push(temp);
                                                                output[currentSection][keyVal.key].push(fixQuoted(keyVal.value));
							} else {
								 output[currentSection][keyVal.key].push(fixQuoted(keyVal.value));
							}
						} else {
							output[currentSection][keyVal.key] = fixQuoted(keyVal.value);
						}

This lets me parse things like this,
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=8 
and turn it into OverridePlayerLevelEngramPoints: [0,8];

**Comment by Ajnasz** [comment]
Could you please take a look at a6494e3dd196fc0233df0b22e099420cd3e0d5ca commit?

**Comment by knightzac19** [comment]
Works like a charm, but I'll need to test this with the other issue's branch as well when you merge because this INI file had the brackets in it too.

**Comment by Ajnasz** [comment]
#8 merged to master and I merged the master into duplicate-names branch, so you can try it!

Thanks :)

**Comment by knightzac19** [comment]
So far so good, I don't see any issues on read/write.

No Problem!
